x-common: &hw_api
  build: .
  restart: unless-stopped

services:
  hw-api:
    <<: *hw_api
    container_name: hw-api
    ports:
      - "8000:8000"
    volumes:
      - .:/data
  pg:
    image: postgres:17
    environment:
      POSTGRES_DB: hwApp
      POSTGRES_USER: sammy
      POSTGRES_PASSWORD: Leto2025
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
