services:
  api:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8000"
    command:
      - "python"
      - "main.py"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

  pg:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - hwApp_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "1009:8080"

volumes:
  hwApp_pg_data:
