services:
  hwApp_bot:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: hwApp_bot
    ports:
      - "8001:8000"
    volumes:
      - .:/data
    command:
      - "python"
      - "main.py"

  hwApp_pg:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - hwApp_pg_data:/var/lib/postgresql/data
volumes:
  hwApp_pg_data:
