services:
  api:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: hw_api-api
    depends_on:
      - db
    ports:
      - "8001:8000"
    command:
      - "uv"
      - "run"
      - "main.py"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: hwApp
      POSTGRES_USER: sammy
      POSTGRES_PASSWORD: Dosya1009
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - hwApp_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: hw_api-adminer
    ports:
      - "1803:8080"
    restart: unless-stopped

volumes:
  hwApp_pg_data:
