services:
  api:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8000"
    command:
      - "python"
      - "main.py"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - hwApp_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "1803:8080"
    restart: unless-stopped

volumes:
  hwApp_pg_data:
