services:
  hw_app_bot:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: hw_app_bot
    ports:
      - "8001:8000"
    command:
      - "python"
      - "main.py"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

  hw_app_pg:
    image: postgres:17
    environment:
      POSTGRES_DB: hwApp
      POSTGRES_USER: sammy
      POSTGRES_PASSWORD: Leto2025
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - hwApp_pg_data:/var/lib/postgresql/data
volumes:
  hwApp_pg_data:
