"""remove uid

Revision ID: 4fd9f62b923d
Revises: ad90849bf68d
Create Date: 2025-08-23 11:39:10.332565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4fd9f62b923d"
down_revision: Union[str, Sequence[str], None] = "ad90849bf68d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "uid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("uid", sa.BIGINT(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
