"""mutable json

Revision ID: 5ac149eb236d
Revises: 43670e750c90
Create Date: 2025-07-26 15:24:38.424496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "5ac149eb236d"
down_revision: Union[str, Sequence[str], None] = "43670e750c90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classess", "schedule")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classess", sa.Column("schedule", sqlite.JSON(), nullable=False))
    # ### end Alembic commands ###
