"""register

Revision ID: 74a75b92cb7f
Revises: 12288941c6c2
Create Date: 2025-08-05 19:09:51.748604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74a75b92cb7f"
down_revision: Union[str, Sequence[str], None] = "12288941c6c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registers",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("email"),
        sa.UniqueConstraint("email"),
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_table("registers")
    # ### end Alembic commands ###
