"""classes table

Revision ID: 917d465125bb
Revises: 2f24b8f9de4c
Create Date: 2025-07-26 12:50:16.445143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "917d465125bb"
down_revision: Union[str, Sequence[str], None] = "2f24b8f9de4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classess",
        sa.Column("class_name", sa.String(), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=False),
        sa.Column("homeworks", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("admins", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classess")
    # ### end Alembic commands ###
