"""uid

Revision ID: ad90849bf68d
Revises: d8d071b478bb
Create Date: 2025-08-23 11:34:26.665915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad90849bf68d"
down_revision: Union[str, Sequence[str], None] = "d8d071b478bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("uid", sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "uid")
    # ### end Alembic commands ###
