"""start

Revision ID: d8d071b478bb
Revises:
Create Date: 2025-08-21 13:45:53.722265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8d071b478bb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classess",
        sa.Column("class_name", sa.String(), nullable=False),
        sa.Column("homeworks", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("admins", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("class_name"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("class_name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("login_dn", sa.String(), nullable=False),
        sa.Column("password_dn", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("email"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("classess")
    # ### end Alembic commands ###
