"""описаниеdel register

Revision ID: f8ce75fec6f0
Revises: 74a75b92cb7f
Create Date: 2025-08-05 16:52:42.989414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8ce75fec6f0"
down_revision: Union[str, Sequence[str], None] = "74a75b92cb7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registers",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("email", name=op.f("registers_pkey")),
    )
    # ### end Alembic commands ###
